cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    ceremoniemeester:
      email: jsmith@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Rachel en Elsemieke
      password: $2b$12$iWlVOac3uujRvTrXDi6wructXftKmo/GyQd6SMu5FmyX306kH.yFO
    Bruiloftsgast:
      email: rbriggs@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Bruiloftsgast
      password: $2b$12$lPkyR2AHrTPiQff8Wq7bBO0AE040j5klCcxeo9gQV0zxBbr6qJM3K
    avondgast:
      email: rcouper@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Avondgast
      password: $2b$12$iWlVOac3uujRvTrXDi6wructXftKmo/GyQd6SMu5FmyX306kH.yFO
    wdewe:
      email: wedw@ew.com
      failed_login_attempts: 0
      logged_in: false
      name: dwew
      password: $2b$12$QJBPc7PxaTTBVJ.3cl4KlOPPqYCWVfaHqkk2IsoGDExXhihKZLDgy
pre-authorized:
  emails:
  - melsby@gmail.com
