type = "service_account"
project_id = "tenacious-works-283209"
private_key_id = "be107c4dfaa63cf63c02b80e47ddb847fe01f50f"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCurtu8X/rP4pKa
8CCMWOISgvLK3UBY0LvcYtZjS6nFfhKiKGDH7NXhgZJq1GgbD0kG7j7/ZKzKvlFc
VAbiwRHHA6XKJ6RpcAmg/BjA1aixs1rA5urwloOsFfhqAbXLIoUYxVzhfbbmltk5
UTCYGItjPMOcVhbYtRw44sxIK1NJiKvekMLWqQmY7TtvDhQ8eNBVVozE3qZx2Bs7
/IZLmeGyKyypE5pQmTWOaPXRlgJ35sbiYMiuR6npwg2CcxxAgz3nt7Q7K3kGSmqh
n2S7TCBFKVMcZNT6viO7osFXMs04gUDpD0FbISmN9L44hYU2yVbDTpCNCWMkaddG
9xCvxevbAgMBAAECggEAF3wHq7AwV+wrRJby8UYZLV7whaiFjaCRGRnVSSfeImCG
4HPS6x339Tzbx+6tiQce4hvRWWREvMR7ILwP6ZgGVqiytyu+4AlW1Ln/w/EVoGpZ
/E7Z7XrMJ1cUJ4BPsLMqjKrVXWAZi6+3yDZrn48b3Oge7kY+r7zNl1zvv5DKPjuJ
0gYfjfmGP/fcfAvtfssWUn8EKHcBFGhokCTqdc+rCFo4gcNPxnHTSgHS2MQpecgD
7dno5elgyUL4KpciIZ9d0qjCVRFX8Ewb6u12f+i/UYzoSYpBfUjOx/2ku8ZruJI7
x7PBtRBsNueFyt/+A+hAMpyik1jR1N5unbl9+pToIQKBgQDvvCyi6c7iqQjReGtd
wG1bK8v6+aRO3u99z1NHgXC/dG0fQmecuLSDO0ZGvgeO/RCsyUna6GIR1hCWzfCE
awpepEPhfmik7PI26UezUgqKhOea+aU0NyWF4gW0KSJxZmRldQxuu2jdTJVI/KPe
cz5mkl2JvF7//NKueAIrgSfvOwKBgQC6iNTceImL7taTSs0bn7jZvTMJUomuQfEn
NQ4WeVNXRCbAdWwvNQy31Ko0xp5BQTwahLHzOd9CVgOKrcUzTirSaSJzHfg3luK0
3AQbu4OIlJNPkpmTF6nVr3OqZRNIntEztIbixipwD6hRUyG+0wzp0olaOSahsLuV
1o+jEx1r4QKBgQDj/irZONDXgPhw9jvtqk6WEV3prrdThvNuy9igvXpzqg8JVobh
ZkvOLnYUWy8nDodoO/pwJOb3nYSjVvGxjXcMMN6ZujVc/DcSf+L/qDt8Jw94tIkn
0nZuEFlqUGCARmeekaWkPblqFSY4hoR1z1X+CJ7KmgojG9dls54kr61B9wKBgH+b
0BMrmt1R/RUynPKC6BB9MIb2Ih5GGlW6I/MX+P3AL8qGCgaZgiPYpsAICIeXuyhh
EuPT+XoGIdIjYr7ggMcFCX47SG2vGVSlF2Jpe2haTBSps8o+6/61UqmFEBYkH/YB
UC2fZ7TV4U4RUwqak0D6uOAyLM18fDfbWtQy5XPBAoGBANrVt37JbYxLZb+mK2LL
UOBPT0l2BAG+NVsyQj0bhiaYIu++9IMNJUV7gXhGavgD0jhbuS/k7heM85ov0XZO
KursowvumkPtF+MxnQVv0TLVkzs2pTd+4RnKqtSbKLM1IKqMwouLAXyiJIEVk3Iy
mGmBN3zKhiB468ophGmoxv/j
-----END PRIVATE KEY-----
"""
client_email = "trouwapi@tenacious-works-283209.iam.gserviceaccount.com"
client_id = "100779753397360662499"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/trouwapi%40tenacious-works-283209.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
